[project]
name = "camera-rpi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.0",
    "numpy>=2.4.0",
    "opencv-contrib-python>=4.11.0.86",
    "uvicorn>=0.40.0",
]
